app:
  name: bff
  image:
    repository: "onecx/onecx-iam-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          user:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
          role:
            read: permission on all GET requests and POST search
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-ia:all, ocx-pm:read  ]